# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BackEndConnectingTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BackEndConnectingTest
	pod 'Alamofire'
	pod 'SwiftyJSON'


end
